### ISSUE TITLE
methyICC for WGBS data of tissue samples

### ISSUE THREAD

**Issue by sunyu1010** [stephaniehicks/methylCC#10]
Hi, thanks for your excellent work :)
This package is designed to estimate the cell composition of whole blood. Can I apply methyICC to esitmate immune cell fractions of WGBS data from tumor tissues?
Thank you so much!

**Comment by stephaniehicks** [comment]
hi @sunyu1010, thanks for your message! That's a great question. We haven't tried it with WGBS data from tumor tissues. The estimates of cell composition wouldn't include estimates of the proportion of tumor cells though, so I might not suggest it. Thanks!

**Comment by sunyu1010** [comment]
Thank you so much！
