### ISSUE TITLE
Error in `colnames<-`(`*tmp*`, value = cell_levels) :  attempt to set 'colnames' on an object with less than two dimensions

### ISSUE THREAD

**Issue by xxz1482** [stephaniehicks/methylCC#7]
Hi,
An issue with estimatecc{methylCC} that I encountered while running with my BSseq object.

**est <- estimatecc(BSseq_obj, include_dmrs = FALSE) 
Error in `colnames<-`(`*tmp*`, value = cell_levels) : 
  attempt to set 'colnames' on an object with less than two dimensions**

Any comments or suggestions are truly appreciated!
Lastly, once we get the cell compositions, could methylCC do cell-specific adjustment on the original WGBS data and return an adjusted WGBS data?
Thanks very much in advance!

**Comment by stephaniehicks** [comment]
Hi, is there a small reprex (**repro**ducible **ex**ample) (https://reprex.tidyverse.org/) you could provide to help me debug the issue? Thanks!

**Comment by xxz1482** [comment]
Hi Dr. Hicks,

Attached, I include an example WGBS data that I used to generate my BSseq object.

[TotalReads.txt](https://github.com/stephaniehicks/methylCC/files/10679755/TotalReads.txt)
[MethylReads.txt](https://github.com/stephaniehicks/methylCC/files/10679756/MethylReads.txt)

**Comment by stephaniehicks** [comment]
Could you also provide the code you are using? Thanks!

**Comment by xxz1482** [comment]
Thanks very much for your helps!
[Rcode.txt](https://github.com/stephaniehicks/methylCC/files/10680391/Rcode.txt)

**Comment by stephaniehicks** [comment]
Hi, 

I am still not sure about the colnames issue. However, this package only estimates the cell composition. It does not return any normalized / adjusted data. Thanks!
