### ISSUE TITLE
Cannot successfully run the script of test-estimatecc.R

### ISSUE THREAD

**Issue by liuyiying0628** [stephaniehicks/methylCC#8]
Dear Dr. Hicks,
I have installed the methylCC Package with version of 1.2.0 under R 4.0.0. However, I cannot successfully run the test-estimatecc.R at
https://github.com/stephaniehicks/methylCC/blob/master/tests/testthat/test-estimatecc.R
The issue here is the following:
>FlowSorted.Blood.450k.sub
class: RGChannelSet
dim: 150000 6
metadata(0):
assays(2): Green Red
rownames(150000): 58715388 43754481 ... 60676484 63741342
rowData names(0):
colnames(6): WB_105 WB_218 ... WB_160 WB_149
colData names(8): Sample_Name Slide ... CellType Sex
Annotation
array: IlluminaHumanMethylation450k
annotation: ilmn12.hg19
>set.seed(12345)
>est <- estimatecc(object = FlowSorted.Blood.450k.sub)
Loading required package: IlluminaHumanMethylation450kmanifest

*** caught segfault ***
address (nil), cause 'unknown'

Traceback:
1: colMeans2(Green, rows = match(CG.controls, rownames(Green)))
2: colMeans2(Green, rows = match(CG.controls, rownames(Green)))
3: normalize.illumina.control(rgSet, reference = reference)
4: preprocessIllumina(FlowSorted.Blood.450k)
5: .find_dmrs(verbose = verbose, include_cpgs = include_cpgs, include_dmrs = include_dmrs)
6: withCallingHandlers(expr, warning = function(w) if (inherits(w, classes)) tryInvokeRestart("muffleWarning"))
7: suppressWarnings(.find_dmrs(verbose = verbose, include_cpgs = include_cpgs, include_dmrs = include_dmrs))
8: estimatecc(object = FlowSorted.Blood.450k.sub)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

What could be the reason for “segfault”?
I look forward to your reply.

Best regards,

**Comment by stephaniehicks** [comment]
Hi, it looks like it's a problem with the normalization step. I'd suggest reaching out to the authors who developed the `preprocessIllumina()` in `minfi` (https://bioconductor.org/packages/minfi). Thanks!
